export const BANNER_LIST_REQUEST_INIT = "BANNER_LIST_REQUEST_INIT";
export const BANNER_LIST_REQUEST_SUCCESS = "BANNER_LIST_REQUEST_SUCCESS";
export const BANNER_LIST_REQUEST_FAILURE = "BANNER_LIST_REQUEST_FAILURE";