export const CATEGORY_LIST_REQUEST_INIT = "CATEGORY_LIST_REQUEST_INIT";
export const CATEGORY_LIST_REQUEST_SUCCESS = "CATEGORY_LIST_REQUEST_SUCCESS";
export const CATEGORY_LIST_REQUEST_FAILURE = "CATEGORY_LIST_REQUEST_FAILURE";