export const PRODUCT_LIST_REQUEST_INIT = "PRODUCT_LIST_REQUEST_INIT";
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAILURE = "PRODUCT_LIST_REQUEST_FAILURE";