name: CI for code push in PS-SKB

on:
    # Triggers the workflow on push event only for the develop branch
    push:
        branches: [develop-main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: yarn install, build and test
              run: |
                  yarn install
                  yarn run build
                  yarn test
